"""Ionic structure and QOZ/HNC interfaces."""
from __future__ import annotations

from otter.ionic.correlation import IonCorrelationModel, IonSphereStepModel, ion_sphere_radius_from_density
from otter.ionic.lfc import (
    LFC_MODEL_CITATION_KEYS,
    LFC_MODEL_REFERENCE_KEYS,
    cee_from_gee,
    cee_jellium_from_lfc,
    chabrier1990_gamma0,
    coupling_parameter_ee_au,
    fermi_energy_au,
    fermi_wavenumber_au,
    gee_jellium,
    gee_jellium_chabrier1990,
    gee_jellium_chabrier_hubbard,
    gee_jellium_geldartvosko,
    gee_jellium_gregori2007,
    gee_jellium_hubbard,
    gee_jellium_utsumiichimaru,
    gee_jellium_vashistasingwi,
    iit_exchange_correlation_free_energy_per_electron_au,
    wigner_seitz_radius_au,
)
from otter.ionic.qoz import (
    EffectivePotentialResult,
    MultiComponentEffectivePotentialResult,
    MultiComponentScreeningChargeConsistencyResult,
    QOZPotentialOptions,
    QOZResponseOptions,
    ScreeningChargeConsistencyResult,
    build_effective_vii_from_nscr,
    build_effective_vij_from_nscr,
    chi0_lindhard_finite_t,
    chi_ee_from_eq17,
    enforce_screening_charge_consistency,
    enforce_screening_charge_consistency_many,
    decompose_effective_pair_potential_k,
    hnc_solver,
    hnc_solver_multicomponent,
    hnc_solver_multicomponent_continuation,
    mu_jellium_from_nbar,
    qoz_zbar_from_nscr,
    radial_charge_trapezoid,
)
from otter.numerics.transforms import (
    dst_lattice_zero_moment,
    precompute_dst_lattice_transform_like,
    radial_forward,
    radial_inverse,
)

__all__ = [
    "EffectivePotentialResult",
    "IonCorrelationModel",
    "IonSphereStepModel",
    "LFC_MODEL_REFERENCE_KEYS",
    "LFC_MODEL_CITATION_KEYS",
    "MultiComponentEffectivePotentialResult",
    "MultiComponentScreeningChargeConsistencyResult",
    "QOZPotentialOptions",
    "QOZResponseOptions",
    "ScreeningChargeConsistencyResult",
    "build_effective_vii_from_nscr",
    "build_effective_vij_from_nscr",
    "cee_from_gee",
    "cee_jellium_from_lfc",
    "chabrier1990_gamma0",
    "chi0_lindhard_finite_t",
    "chi_ee_from_eq17",
    "coupling_parameter_ee_au",
    "decompose_effective_pair_potential_k",
    "dst_lattice_zero_moment",
    "enforce_screening_charge_consistency",
    "enforce_screening_charge_consistency_many",
    "fermi_energy_au",
    "fermi_wavenumber_au",
    "gee_jellium",
    "gee_jellium_chabrier1990",
    "gee_jellium_chabrier_hubbard",
    "gee_jellium_geldartvosko",
    "gee_jellium_gregori2007",
    "gee_jellium_hubbard",
    "gee_jellium_utsumiichimaru",
    "gee_jellium_vashistasingwi",
    "hnc_solver",
    "hnc_solver_multicomponent",
    "hnc_solver_multicomponent_continuation",
    "ion_sphere_radius_from_density",
    "iit_exchange_correlation_free_energy_per_electron_au",
    "mu_jellium_from_nbar",
    "precompute_dst_lattice_transform_like",
    "radial_forward",
    "radial_inverse",
    "qoz_zbar_from_nscr",
    "radial_charge_trapezoid",
    "wigner_seitz_radius_au",
]
